POST http://localhost:8080/books
content-type: application/json

{
    "title": "O Senhor dos Anéis - Livro 1",
    "author": "J.R.R. Tolkien"
}

###
GET http://localhost:8080/books

###
GET http://localhost:8080/books/631cd7139e59b4288b74e7b9